### ISSUE TITLE
Readme incorrectly states default stratgegy

### ISSUE THREAD

**Issue by JohannesRudolph** [EugenMayer/docker-image-concourseci-worker-solid#2]
Readme says: 
> You can change the default strategy to unregister workers from land-worker to retire-worker by simply

but wrapper script says: 

```bash
set -e
# could be land-worker or retire worker
strategy=${1:-retire-worker}
```

Looks to me like retire-worker is the default, rather than land-worker?

Big thanks for providing this image (and being so fast updating to 3.10 too 👍 )!!!

**Comment by EugenMayer** [comment]
you are right, it changed and i forgot to upgrade the readme. fixed. Thanks for the heads up!
